In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [5]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostRegressor

param_grid = {
    'n_estimators': [10, 25, 50, 100, 200, 500],
    'learning_rate': [0.001, 0.01, 0.1, 0.5, 1.0, 2.0],
    'loss': ['linear', 'square', 'exponential']
}

grid=GridSearchCV(AdaBoostRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 108 candidates, totalling 540 fits

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=AdaBoostRegressor(), n_jobs=-1,
             param_grid={'learning_rate': [0.001, 0.01, 0.1, 0.5, 1.0, 2.0],
                         'loss': ['linear', 'square', 'exponential'],
                         'n_estimators': [10, 25, 50, 100, 200, 500]},
             verbose=3)

In [7]:
re=grid.cv_results_
print("The R_score value for best parameter {}".format(grid.best_params_))

The R_score value for best parameter {'learning_rate': 0.1, 'loss': 'linear', 'n_estimators': 10}

In [8]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_loss,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.239532,0.043858,0.036349,0.005937,0.001,linear,10,"{'learning_rate': 0.001, 'loss': 'linear', 'n_...",0.875475,0.791540,0.880807,0.827312,0.856486,0.846324,0.033181,31
1,0.506812,0.075252,0.046065,0.011732,0.001,linear,25,"{'learning_rate': 0.001, 'loss': 'linear', 'n_...",0.871667,0.794524,0.880830,0.827551,0.863120,0.847538,0.032073,25
2,1.027697,0.109699,0.082803,0.009330,0.001,linear,50,"{'learning_rate': 0.001, 'loss': 'linear', 'n_...",0.876231,0.794679,0.882211,0.829820,0.863239,0.849236,0.032758,6
3,2.155388,0.053126,0.138221,0.009549,0.001,linear,100,"{'learning_rate': 0.001, 'loss': 'linear', 'n_...",0.872929,0.795223,0.882077,0.828674,0.862916,0.848364,0.032135,12
4,4.544269,0.085758,0.275287,0.021933,0.001,linear,200,"{'learning_rate': 0.001, 'loss': 'linear', 'n_...",0.874875,0.793067,0.881008,0.829772,0.862350,0.848214,0.032764,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,0.648009,0.018140,0.057448,0.005695,2.000,exponential,25,"{'learning_rate': 2.0, 'loss': 'exponential', ...",0.615412,0.517018,0.559851,0.575800,0.584654,0.570547,0.032309,83
104,1.322788,0.029316,0.104806,0.016085,2.000,exponential,50,"{'learning_rate': 2.0, 'loss': 'exponential', ...",0.539093,0.447105,0.493078,0.540482,0.520545,0.508061,0.034957,87
105,2.517070,0.082963,0.183104,0.015719,2.000,exponential,100,"{'learning_rate': 2.0, 'loss': 'exponential', ...",0.530472,0.399033,0.472693,0.460195,0.482485,0.468976,0.042302,96
106,5.440707,0.078956,0.341503,0.051902,2.000,exponential,200,"{'learning_rate': 2.0, 'loss': 'exponential', ...",0.519066,0.359673,0.449209,0.441914,0.466702,0.447313,0.051455,100
107,10.412373,0.320759,0.563198,0.085460,2.000,exponential,500,"{'learning_rate': 2.0, 'loss': 'exponential', ...",0.524156,0.349360,0.430344,0.432187,0.461662,0.439542,0.056428,104

In [9]:
age_input = float(input("Enter Age:::"))
bmi_input = float(input("Enter bmi:::"))
childern_input = float(input("Childern:::"))
sex_male_input = int(input("Sex Male 0 or  1:"))
smoker_yes_input = int(input("Smoker Yes 0 or 1"))

Enter Age::: 32
Enter bmi::: 43
Childern::: 2
Sex Male 0 or  1: 1
Smoker Yes 0 or 1 0

In [10]:
Future_Predictions=grid.predict([[age_input,bmi_input,childern_input,sex_male_input,smoker_yes_input]])
Future_Predictions

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but AdaBoostRegressor was fitted with feature names
  warnings.warn(

array([7175.67261634])