In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [5]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [6]:
from sklearn.model_selection import GridSearchCV
from lightgbm import LGBMRegressor
param_grid = {
    'n_estimators': [50, 100, 200]
     }
grid=GridSearchCV(LGBMRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000275 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 313
[LightGBM] [Info] Number of data points in the train set: 1338, number of used features: 5
[LightGBM] [Info] Start training from score 13270.422260

GridSearchCV(estimator=LGBMRegressor(), n_jobs=-1,
             param_grid={'n_estimators': [50, 100, 200]}, verbose=3)

In [7]:
C

The R_score value for best parameter {'n_estimators': 50}

In [8]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,2.143130,0.245874,0.009863,0.002006,50,{'n_estimators': 50},0.869489,0.792229,0.882418,0.837704,0.856842,0.847736,0.031435,1
1,1.955099,1.089295,0.011066,0.001939,100,{'n_estimators': 100},0.857835,0.776793,0.868698,0.831484,0.849952,0.836953,0.032440,2
2,1.657399,0.100974,0.012389,0.001484,200,{'n_estimators': 200},0.844661,0.758038,0.858333,0.823464,0.836148,0.824129,0.034941,3

In [9]:
age_input = float(input("Enter Age:::"))
bmi_input = float(input("Enter bmi:::"))
childern_input = float(input("Childern:::"))
sex_male_input = int(input("Sex Male 0 or  1:"))
smoker_yes_input = int(input("Smoker Yes 0 or 1"))

Enter Age::: 32
Enter bmi::: 43
Childern::: 2
Sex Male 0 or  1: 1
Smoker Yes 0 or 1 0

In [12]:
Future_Predictions=grid.predict([[age_input,bmi_input,childern_input,sex_male_input,smoker_yes_input]])
Future_Predictions

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

array([4134.2165097])