In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [5]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingRegressor
param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.2, 0.3],
    'max_depth': [3, 5, 7]
  
}


grid=GridSearchCV(GradientBoostingRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

GridSearchCV(estimator=GradientBoostingRegressor(), n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 0.2, 0.3],
                         'max_depth': [3, 5, 7],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [7]:
re=grid.cv_results_
print("The R_score value for best parameter {}".format(grid.best_params_))

The R_score value for best parameter {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 50}

In [8]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.067248,0.078657,0.049326,0.008376,0.01,3,50,"{'learning_rate': 0.01, 'max_depth': 3, 'n_est...",0.557956,0.523039,0.532953,0.544998,0.540986,0.539987,0.011711,36
1,2.199898,0.101549,0.053647,0.004707,0.01,3,100,"{'learning_rate': 0.01, 'max_depth': 3, 'n_est...",0.764509,0.710576,0.740231,0.738270,0.742472,0.739212,0.017161,32
2,3.763577,0.526940,0.040932,0.027367,0.01,3,200,"{'learning_rate': 0.01, 'max_depth': 3, 'n_est...",0.868811,0.797977,0.860857,0.838070,0.847522,0.842647,0.024724,7
3,1.455368,0.010034,0.055979,0.007009,0.01,5,50,"{'learning_rate': 0.01, 'max_depth': 5, 'n_est...",0.565891,0.524420,0.542600,0.546315,0.541099,0.544065,0.013254,34
4,2.715754,0.213973,0.050110,0.020850,0.01,5,100,"{'learning_rate': 0.01, 'max_depth': 5, 'n_est...",0.768714,0.708994,0.752746,0.737543,0.741357,0.741871,0.019691,31
5,4.595103,1.225823,0.047980,0.030107,0.01,5,200,"{'learning_rate': 0.01, 'max_depth': 5, 'n_est...",0.865052,0.791402,0.866196,0.826878,0.845462,0.838998,0.027830,9
6,0.992268,0.592230,0.032018,0.027531,0.01,7,50,"{'learning_rate': 0.01, 'max_depth': 7, 'n_est...",0.567671,0.516028,0.553226,0.535109,0.530058,0.540418,0.018095,35
7,3.042223,1.054459,0.053467,0.022407,0.01,7,100,"{'learning_rate': 0.01, 'max_depth': 7, 'n_est...",0.758847,0.694810,0.755429,0.719744,0.726011,0.730968,0.023806,33
8,6.759077,1.622671,0.094295,0.010260,0.01,7,200,"{'learning_rate': 0.01, 'max_depth': 7, 'n_est...",0.841961,0.775677,0.851962,0.799553,0.824343,0.818699,0.027917,14
9,0.898772,0.303445,0.040481,0.017077,0.10,3,50,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.883026,0.805421,0.890918,0.850846,0.866315,0.859305,0.030286,1
10,2.204649,0.061827,0.048358,0.008089,0.10,3,100,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.874739,0.799233,0.890776,0.846596,0.858382,0.853945,0.031164,2
11,3.967102,0.585453,0.041182,0.017712,0.10,3,200,"{'learning_rate': 0.1, 'max_depth': 3, 'n_esti...",0.863133,0.778309,0.884200,0.839727,0.850350,0.843144,0.035644,6
12,1.433094,0.024982,0.049109,0.010365,0.10,5,50,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.868091,0.790149,0.882754,0.833335,0.854984,0.845863,0.032247,5
13,1.914583,0.667811,0.038046,0.023744,0.10,5,100,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.857781,0.769494,0.870113,0.824850,0.843377,0.833123,0.035209,10
14,5.312543,0.557220,0.065204,0.029709,0.10,5,200,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.833960,0.737267,0.854731,0.813235,0.828389,0.813516,0.040378,17
15,1.834462,0.073039,0.060602,0.007208,0.10,7,50,"{'learning_rate': 0.1, 'max_depth': 7, 'n_esti...",0.835709,0.765855,0.854229,0.797533,0.832134,0.817092,0.031495,15
16,3.503645,0.317796,0.057261,0.023322,0.10,7,100,"{'learning_rate': 0.1, 'max_depth': 7, 'n_esti...",0.813268,0.752058,0.842249,0.786867,0.824335,0.803755,0.031476,20
17,7.159539,0.161808,0.072818,0.009119,0.10,7,200,"{'learning_rate': 0.1, 'max_depth': 7, 'n_esti...",0.801132,0.731717,0.831357,0.777995,0.818371,0.792114,0.035094,24
18,1.151572,0.083621,0.047353,0.009454,0.20,3,50,"{'learning_rate': 0.2, 'max_depth': 3, 'n_esti...",0.875320,0.796599,0.889096,0.846790,0.857037,0.852968,0.031740,3
19,2.106588,0.125142,0.050012,0.011245,0.20,3,100,"{'learning_rate': 0.2, 'max_depth': 3, 'n_esti...",0.862455,0.773590,0.881071,0.838369,0.848691,0.840835,0.036541,8
20,3.631259,0.901605,0.037250,0.022161,0.20,3,200,"{'learning_rate': 0.2, 'max_depth': 3, 'n_esti...",0.837680,0.738289,0.870920,0.828690,0.834541,0.822024,0.044381,13
21,1.134608,0.478626,0.032667,0.023802,0.20,5,50,"{'learning_rate': 0.2, 'max_depth': 5, 'n_esti...",0.848735,0.771245,0.868308,0.828596,0.839954,0.831368,0.032749,12
22,2.110239,0.988451,0.038108,0.023976,0.20,5,100,"{'learning_rate': 0.2, 'max_depth': 5, 'n_esti...",0.826771,0.750616,0.846508,0.813992,0.826576,0.812893,0.032831,18
23,3.354133,1.618179,0.023403,0.024556,0.20,5,200,"{'learning_rate': 0.2, 'max_depth': 5, 'n_esti...",0.808501,0.727463,0.832183,0.802118,0.810245,0.796102,0.035786,22
24,1.956646,0.056952,0.048415,0.020886,0.20,7,50,"{'learning_rate': 0.2, 'max_depth': 7, 'n_esti...",0.816353,0.733854,0.835897,0.791492,0.818519,0.799223,0.035619,21
25,3.858801,0.397528,0.067861,0.031817,0.20,7,100,"{'learning_rate': 0.2, 'max_depth': 7, 'n_esti...",0.809395,0.722743,0.829122,0.786097,0.810931,0.791658,0.037067,25
26,8.133828,0.170317,0.084327,0.015276,0.20,7,200,"{'learning_rate': 0.2, 'max_depth': 7, 'n_esti...",0.804849,0.711477,0.829145,0.783948,0.807632,0.787410,0.040578,26
27,1.294876,0.062067,0.046968,0.008263,0.30,3,50,"{'learning_rate': 0.3, 'max_depth': 3, 'n_esti...",0.862846,0.792328,0.882295,0.842444,0.852050,0.846393,0.030101,4
28,2.195954,0.391512,0.045963,0.021451,0.30,3,100,"{'learning_rate': 0.3, 'max_depth': 3, 'n_esti...",0.850473,0.769201,0.872759,0.829793,0.837989,0.832043,0.034604,11
29,3.285489,1.146219,0.026319,0.024298,0.30,3,200,"{'learning_rate': 0.3, 'max_depth': 3, 'n_esti...",0.825015,0.731249,0.848835,0.815137,0.816037,0.807255,0.039901,19
30,1.129710,0.627177,0.034569,0.025383,0.30,5,50,"{'learning_rate': 0.3, 'max_depth': 5, 'n_esti...",0.835357,0.742371,0.860490,0.798645,0.836922,0.814757,0.041247,16
31,2.365846,1.107806,0.041008,0.029156,0.30,5,100,"{'learning_rate': 0.3, 'max_depth': 5, 'n_esti...",0.809816,0.718841,0.843771,0.783561,0.822536,0.795705,0.043093,23
32,5.760276,1.062415,0.080443,0.014127,0.30,5,200,"{'learning_rate': 0.3, 'max_depth': 5, 'n_esti...",0.795082,0.700579,0.829519,0.773439,0.816732,0.783070,0.045459,27
33,1.959055,0.125276,0.045702,0.018270,0.30,7,50,"{'learning_rate': 0.3, 'max_depth': 7, 'n_esti...",0.806901,0.716109,0.821377,0.767393,0.798827,0.782121,0.037440,28
34,4.421531,0.197456,0.067401,0.017535,0.30,7,100,"{'learning_rate': 0.3, 'max_depth': 7, 'n_esti...",0.800147,0.707836,0.818149,0.768293,0.790247,0.776935,0.038116,30
35,9.044220,0.190657,0.100767,0.008076,0.30,7,200,"{'learning_rate': 0.3, 'max_depth': 7, 'n_esti...",0.801232,0.708028,0.816811,0.765013,0.795384,0.777294,0.038498,29

In [9]:
age_input = float(input("Enter Age:::"))
bmi_input = float(input("Enter bmi:::"))
childern_input = float(input("Childern:::"))
sex_male_input = int(input("Sex Male 0 or  1:"))
smoker_yes_input = int(input("Smoker Yes 0 or 1"))

Enter Age::: 32
Enter bmi::: 43
Childern::: 2
Sex Male 0 or  1: 1
Smoker Yes 0 or 1 0

In [16]:
Future_Predictions=grid.predict([[age_input,bmi_input,childern_input,sex_male_input,smoker_yes_input]])
Future_Predictions

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(

array([6772.61896378])