In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")
print("No of Columns:", dataset.shape[1])
print("No of Rows:", dataset.shape[0])
dataset

No of Columns: 25
No of Rows: 399

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
print("No of Columns:", dataset.shape[1])
print("No of Rows:", dataset.shape[0])
dataset

No of Columns: 28
No of Rows: 399

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

dependent=dataset[['classification_yes']]

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [6]:

from sklearn.model_selection import GridSearchCV 
from sklearn.linear_model import LogisticRegression
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear'],
    'max_iter': [100, 500, 1000]
}

grid=GridSearchCV(LogisticRegression(),param_grid,refit=True,n_jobs=-1, cv=5, scoring='f1_weighted')
grid.fit(X_train,y_train)

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'max_iter': [100, 500, 1000], 'penalty': ['l1', 'l2'],
                         'solver': ['liblinear']},
             scoring='f1_weighted')

In [7]:
re=grid.cv_results_
grid_prediction = grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test,grid_prediction)

from sklearn.metrics import f1_score
f1_macro = f1_score(y_test,grid_prediction,average='weighted')

print("Best Model {}:", format(grid.best_params_),f1_macro)

Best Model {}: {'C': 10, 'max_iter': 100, 'penalty': 'l1', 'solver': 'liblinear'} 0.975053470019913

In [8]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9985185185185186

In [9]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_max_iter,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.014425,0.001634,0.015217,0.003504,0.01,100,l1,liblinear,"{'C': 0.01, 'max_iter': 100, 'penalty': 'l1', ...",0.874356,0.876368,0.875548,0.892857,0.963636,0.896553,0.034220,28
1,0.017208,0.005856,0.014979,0.002965,0.01,100,l2,liblinear,"{'C': 0.01, 'max_iter': 100, 'penalty': 'l2', ...",0.946153,0.929513,0.911105,0.947015,0.963247,0.939406,0.017723,25
2,0.008115,0.001249,0.012789,0.002027,0.01,500,l1,liblinear,"{'C': 0.01, 'max_iter': 500, 'penalty': 'l1', ...",0.874356,0.876368,0.875548,0.892857,0.963636,0.896553,0.034220,28
3,0.010158,0.001598,0.011466,0.001276,0.01,500,l2,liblinear,"{'C': 0.01, 'max_iter': 500, 'penalty': 'l2', ...",0.946153,0.929513,0.911105,0.947015,0.963247,0.939406,0.017723,25
4,0.007577,0.001821,0.010115,0.000682,0.01,1000,l1,liblinear,"{'C': 0.01, 'max_iter': 1000, 'penalty': 'l1',...",0.874356,0.876368,0.875548,0.892857,0.963636,0.896553,0.034220,28
5,0.008358,0.002565,0.011674,0.001538,0.01,1000,l2,liblinear,"{'C': 0.01, 'max_iter': 1000, 'penalty': 'l2',...",0.946153,0.929513,0.911105,0.947015,0.963247,0.939406,0.017723,25
6,0.010453,0.001976,0.011879,0.001538,0.10,100,l1,liblinear,"{'C': 0.1, 'max_iter': 100, 'penalty': 'l1', '...",0.946153,0.929144,0.929144,0.929144,0.981728,0.943063,0.020424,22
7,0.010572,0.001525,0.011936,0.001792,0.10,100,l2,liblinear,"{'C': 0.1, 'max_iter': 100, 'penalty': 'l2', '...",0.982051,0.964286,0.964572,0.911105,1.000000,0.964403,0.029730,19
8,0.013791,0.005364,0.013030,0.001632,0.10,500,l1,liblinear,"{'C': 0.1, 'max_iter': 500, 'penalty': 'l1', '...",0.946153,0.911105,0.929144,0.929144,0.981728,0.939455,0.023867,24
9,0.010647,0.001941,0.010042,0.000970,0.10,500,l2,liblinear,"{'C': 0.1, 'max_iter': 500, 'penalty': 'l2', '...",0.982051,0.964286,0.964572,0.911105,1.000000,0.964403,0.029730,19
10,0.010229,0.000927,0.011679,0.001127,0.10,1000,l1,liblinear,"{'C': 0.1, 'max_iter': 1000, 'penalty': 'l1', ...",0.946153,0.929144,0.929144,0.929144,0.981728,0.943063,0.020424,22
11,0.009717,0.001545,0.010538,0.001880,0.10,1000,l2,liblinear,"{'C': 0.1, 'max_iter': 1000, 'penalty': 'l2', ...",0.982051,0.964286,0.964572,0.911105,1.000000,0.964403,0.029730,19
12,0.017758,0.003327,0.011508,0.001174,1.00,100,l1,liblinear,"{'C': 1, 'max_iter': 100, 'penalty': 'l1', 'so...",1.000000,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,16
13,0.009954,0.001336,0.012627,0.003453,1.00,100,l2,liblinear,"{'C': 1, 'max_iter': 100, 'penalty': 'l2', 'so...",1.000000,0.964286,0.982221,0.964286,1.000000,0.982159,0.015972,10
14,0.019572,0.003088,0.014519,0.001524,1.00,500,l1,liblinear,"{'C': 1, 'max_iter': 500, 'penalty': 'l1', 'so...",1.000000,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,16
15,0.012092,0.000756,0.014099,0.003288,1.00,500,l2,liblinear,"{'C': 1, 'max_iter': 500, 'penalty': 'l2', 'so...",1.000000,0.964286,0.982221,0.964286,1.000000,0.982159,0.015972,10
16,0.021232,0.005020,0.011985,0.001346,1.00,1000,l1,liblinear,"{'C': 1, 'max_iter': 1000, 'penalty': 'l1', 's...",0.982051,0.963889,0.964572,0.964286,1.000000,0.974960,0.014295,18
17,0.009020,0.000555,0.010844,0.001887,1.00,1000,l2,liblinear,"{'C': 1, 'max_iter': 1000, 'penalty': 'l2', 's...",1.000000,0.964286,0.982221,0.964286,1.000000,0.982159,0.015972,10
18,0.015289,0.005468,0.010215,0.000761,10.00,100,l1,liblinear,"{'C': 10, 'max_iter': 100, 'penalty': 'l1', 's...",0.964572,1.000000,0.982221,0.982221,1.000000,0.985803,0.013263,1
19,0.009244,0.001539,0.011424,0.002205,10.00,100,l2,liblinear,"{'C': 10, 'max_iter': 100, 'penalty': 'l2', 's...",1.000000,0.982051,0.982221,0.964286,1.000000,0.985712,0.013364,2
20,0.014003,0.000772,0.013302,0.002977,10.00,500,l1,liblinear,"{'C': 10, 'max_iter': 500, 'penalty': 'l1', 's...",0.982221,1.000000,0.982221,0.982221,0.981894,0.985711,0.007145,5
21,0.008816,0.001464,0.010372,0.001315,10.00,500,l2,liblinear,"{'C': 10, 'max_iter': 500, 'penalty': 'l2', 's...",1.000000,0.982051,0.982221,0.964286,1.000000,0.985712,0.013364,2
22,0.019683,0.006997,0.010025,0.001457,10.00,1000,l1,liblinear,"{'C': 10, 'max_iter': 1000, 'penalty': 'l1', '...",0.982221,1.000000,0.982221,0.982221,0.981894,0.985711,0.007145,5
23,0.009147,0.001313,0.009708,0.001903,10.00,1000,l2,liblinear,"{'C': 10, 'max_iter': 1000, 'penalty': 'l2', '...",1.000000,0.982051,0.982221,0.964286,1.000000,0.985712,0.013364,2
24,0.010560,0.002333,0.013459,0.003591,100.00,100,l1,liblinear,"{'C': 100, 'max_iter': 100, 'penalty': 'l1', '...",0.982221,0.964286,0.982221,0.982221,0.981894,0.978569,0.007143,15
25,0.007291,0.000771,0.010710,0.000639,100.00,100,l2,liblinear,"{'C': 100, 'max_iter': 100, 'penalty': 'l2', '...",1.000000,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,7
26,0.010769,0.002664,0.011096,0.001718,100.00,500,l1,liblinear,"{'C': 100, 'max_iter': 500, 'penalty': 'l1', '...",0.982221,0.982051,0.982221,0.982221,0.981894,0.982122,0.000132,13
27,0.009114,0.001257,0.010288,0.001450,100.00,500,l2,liblinear,"{'C': 100, 'max_iter': 500, 'penalty': 'l2', '...",1.000000,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,7
28,0.009166,0.001343,0.011438,0.000942,100.00,1000,l1,liblinear,"{'C': 100, 'max_iter': 1000, 'penalty': 'l1', ...",0.982221,0.982051,0.982221,0.982221,0.981894,0.982122,0.000132,13
29,0.010614,0.002129,0.010253,0.002769,100.00,1000,l2,liblinear,"{'C': 100, 'max_iter': 1000, 'penalty': 'l2', ...",1.000000,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,7

In [11]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_max_iter,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.078609,0.005582,0.073637,0.012143,0.01,100,l1,liblinear,"{'C': 0.01, 'max_iter': 100, 'penalty': 'l1', ...",0.874356,0.876368,0.875548,0.892857,0.963636,0.896553,0.034220,28
1,0.071242,0.020952,0.065175,0.012164,0.01,100,l2,liblinear,"{'C': 0.01, 'max_iter': 100, 'penalty': 'l2', ...",0.946153,0.929513,0.911105,0.947015,0.963247,0.939406,0.017723,25
2,0.043625,0.005538,0.061463,0.007401,0.01,500,l1,liblinear,"{'C': 0.01, 'max_iter': 500, 'penalty': 'l1', ...",0.874356,0.876368,0.875548,0.892857,0.963636,0.896553,0.034220,28
3,0.037539,0.006523,0.063463,0.014217,0.01,500,l2,liblinear,"{'C': 0.01, 'max_iter': 500, 'penalty': 'l2', ...",0.946153,0.929513,0.911105,0.947015,0.963247,0.939406,0.017723,25
4,0.039584,0.007010,0.073220,0.010029,0.01,1000,l1,liblinear,"{'C': 0.01, 'max_iter': 1000, 'penalty': 'l1',...",0.874356,0.876368,0.875548,0.892857,0.963636,0.896553,0.034220,28
5,0.038980,0.002896,0.056680,0.004421,0.01,1000,l2,liblinear,"{'C': 0.01, 'max_iter': 1000, 'penalty': 'l2',...",0.946153,0.929513,0.911105,0.947015,0.963247,0.939406,0.017723,25
6,0.059722,0.006794,0.062808,0.009187,0.10,100,l1,liblinear,"{'C': 0.1, 'max_iter': 100, 'penalty': 'l1', '...",0.946153,0.929144,0.929144,0.929144,0.981728,0.943063,0.020424,22
7,0.050294,0.010376,0.075372,0.013416,0.10,100,l2,liblinear,"{'C': 0.1, 'max_iter': 100, 'penalty': 'l2', '...",0.982051,0.964286,0.964572,0.911105,1.000000,0.964403,0.029730,19
8,0.065123,0.008300,0.082231,0.008982,0.10,500,l1,liblinear,"{'C': 0.1, 'max_iter': 500, 'penalty': 'l1', '...",0.946153,0.929144,0.929144,0.929144,0.981728,0.943063,0.020424,22
9,0.059077,0.002640,0.079088,0.012403,0.10,500,l2,liblinear,"{'C': 0.1, 'max_iter': 500, 'penalty': 'l2', '...",0.982051,0.964286,0.964572,0.911105,1.000000,0.964403,0.029730,19
10,0.072923,0.011863,0.084114,0.004227,0.10,1000,l1,liblinear,"{'C': 0.1, 'max_iter': 1000, 'penalty': 'l1', ...",0.946153,0.929144,0.929144,0.929144,0.981728,0.943063,0.020424,22
11,0.063889,0.004465,0.079854,0.008076,0.10,1000,l2,liblinear,"{'C': 0.1, 'max_iter': 1000, 'penalty': 'l2', ...",0.982051,0.964286,0.964572,0.911105,1.000000,0.964403,0.029730,19
12,0.113262,0.012674,0.076503,0.010984,1.00,100,l1,liblinear,"{'C': 1, 'max_iter': 100, 'penalty': 'l1', 'so...",1.000000,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,14
13,0.054094,0.016310,0.071369,0.024468,1.00,100,l2,liblinear,"{'C': 1, 'max_iter': 100, 'penalty': 'l2', 'so...",1.000000,0.964286,0.982221,0.964286,1.000000,0.982159,0.015972,9
14,0.114451,0.029122,0.104004,0.013923,1.00,500,l1,liblinear,"{'C': 1, 'max_iter': 500, 'penalty': 'l1', 'so...",1.000000,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,14
15,0.067933,0.006975,0.091269,0.013457,1.00,500,l2,liblinear,"{'C': 1, 'max_iter': 500, 'penalty': 'l2', 'so...",1.000000,0.964286,0.982221,0.964286,1.000000,0.982159,0.015972,9
16,0.114173,0.024606,0.100094,0.007309,1.00,1000,l1,liblinear,"{'C': 1, 'max_iter': 1000, 'penalty': 'l1', 's...",1.000000,0.963889,0.964572,0.964286,1.000000,0.978549,0.017516,14
17,0.069095,0.011510,0.094228,0.011532,1.00,1000,l2,liblinear,"{'C': 1, 'max_iter': 1000, 'penalty': 'l2', 's...",1.000000,0.964286,0.982221,0.964286,1.000000,0.982159,0.015972,9
18,0.121620,0.031953,0.073234,0.009233,10.00,100,l1,liblinear,"{'C': 10, 'max_iter': 100, 'penalty': 'l1', 's...",0.964572,1.000000,0.982221,0.964286,0.981894,0.978595,0.013294,13
19,0.066664,0.007528,0.072367,0.019973,10.00,100,l2,liblinear,"{'C': 10, 'max_iter': 100, 'penalty': 'l2', 's...",1.000000,0.982051,0.982221,0.964286,1.000000,0.985712,0.013364,1
20,0.110745,0.025196,0.083686,0.002943,10.00,500,l1,liblinear,"{'C': 10, 'max_iter': 500, 'penalty': 'l1', 's...",0.964572,1.000000,0.982221,0.982221,0.981894,0.982182,0.011204,8
21,0.065933,0.013104,0.078469,0.011859,10.00,500,l2,liblinear,"{'C': 10, 'max_iter': 500, 'penalty': 'l2', 's...",1.000000,0.982051,0.982221,0.964286,1.000000,0.985712,0.013364,1
22,0.106669,0.025826,0.078464,0.016244,10.00,1000,l1,liblinear,"{'C': 10, 'max_iter': 1000, 'penalty': 'l1', '...",0.964572,1.000000,0.982221,0.964286,1.000000,0.982216,0.015908,4
23,0.063928,0.011558,0.089648,0.008022,10.00,1000,l2,liblinear,"{'C': 10, 'max_iter': 1000, 'penalty': 'l2', '...",1.000000,0.982051,0.982221,0.964286,1.000000,0.985712,0.013364,1
24,0.085867,0.018185,0.081760,0.010893,100.00,100,l1,liblinear,"{'C': 100, 'max_iter': 100, 'penalty': 'l1', '...",0.982221,0.982051,0.982221,0.982221,0.981894,0.982122,0.000132,12
25,0.071589,0.005519,0.080734,0.009560,100.00,100,l2,liblinear,"{'C': 100, 'max_iter': 100, 'penalty': 'l2', '...",1.000000,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,5
26,0.090388,0.034554,0.080601,0.007754,100.00,500,l1,liblinear,"{'C': 100, 'max_iter': 500, 'penalty': 'l1', '...",0.964572,0.964286,0.982221,0.964286,0.981894,0.971452,0.008661,18
27,0.062334,0.007532,0.076123,0.009732,100.00,500,l2,liblinear,"{'C': 100, 'max_iter': 500, 'penalty': 'l2', '...",1.000000,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,5
28,0.070969,0.014772,0.076058,0.008945,100.00,1000,l1,liblinear,"{'C': 100, 'max_iter': 1000, 'penalty': 'l1', ...",0.982221,0.982051,0.982221,0.982221,0.963912,0.978525,0.007307,17
29,0.059256,0.006468,0.062693,0.015547,100.00,1000,l2,liblinear,"{'C': 100, 'max_iter': 1000, 'penalty': 'l2', ...",1.000000,0.982051,0.964572,0.964286,1.000000,0.982182,0.015908,5

In [10]:
Future_Predictions = grid.predict([[
    45,      # age
    80,      # bp
    1,       # al
    0,       # su
    121,     # bgr
    36,      # bu
    1.2,     # sc
    138,     # sod
    4.5,     # pot
    15.2,    # hrmo
    44,      # pcv
    7800,    # wc
    5.1,     # rc
    0,       # sg_b
    0,       # sg_c
    1,       # sg_d
    0,       # sg_e
    1,       # rbc_normal
    1,       # pc_normal
    0,       # pcc_present
    0,       # ba_present
    1,       # htn_yes
    1,       # dm_yes
    0,       # cad_yes
    1,       # appet_yes
    0,       # pe_yes
    0        # ane_yes
]])

print(Future_Predictions)

[1]

C:\Users\Poorni Gnaneswaran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(